# Generated by Django 3.1.5 on 2021-06-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='hi', max_length=1000),
            preserve_default=False,
        ),
    ]
