# Generated by Django 3.1.5 on 2021-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invoice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Model',
            field=models.CharField(max_length=200),
        ),
    ]
