# Generated by Django 3.1.5 on 2021-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210624_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='final',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Itype',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Bill', 'Credit Bill'), ('Goods Return', 'Goods Return')], default=('Cash', 'Cash'), max_length=100),
        ),
    ]
