# Generated by Django 3.1.5 on 2021-06-29 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210624_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_group',
            name='type',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
