# Generated by Django 3.1.5 on 2021-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210629_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_group',
            name='type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liabilities', 'Liabilities'), ('Debtors', 'Debtors'), ('Creditors', 'Creditors')], default=('Liabilities', 'Liabilities'), max_length=100, verbose_name='Asset'),
        ),
    ]
