# Generated by Django 3.1.5 on 2021-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210629_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='dg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
    ]
