# Generated by Django 3.1.5 on 2021-06-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_group',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dg'),
        ),
    ]
