# Generated by Django 3.1.5 on 2021-06-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210629_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='df',
            fields=[
                ('default_group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.default_group')),
            ],
            bases=('accounts.default_group',),
        ),
    ]
