# Generated by Django 3.1.5 on 2021-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210629_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_group',
            name='df',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
