# Generated by Django 3.1.5 on 2021-06-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_default_group_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_center',
            name='df',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='df',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
