# Generated by Django 3.1.5 on 2021-06-30 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210630_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
