# Generated by Django 3.1.5 on 2021-06-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_center',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cost_Center', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='ltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cost_Center', to='accounts.ledger'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ledger', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ledger', to='accounts.default_group'),
        ),
    ]
