# Generated by Django 3.1.5 on 2021-07-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210706_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='dlsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Invoices', models.ManyToManyField(to='accounts.Invoice')),
                ('Purchases', models.ManyToManyField(to='accounts.Purchase')),
                ('Receipts', models.ManyToManyField(to='accounts.Receipt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlsheet', to='accounts.company')),
                ('fy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlsheet', to='accounts.financial_year')),
            ],
        ),
    ]
