# Generated by Django 3.1.5 on 2021-07-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_dlsheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='Name',
        ),
    ]
