# Generated by Django 3.1.5 on 2021-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210726_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='cc',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
